# Claim a portion of the storage allocated for the Selene Skill Service for
# storage of the database data.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skill-db-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi