# Base configuration to build and run the skill service
#
# By design, there are no default values in this file.  Everything specified
# below applies to all environments.  This prevents bad default values from
# being used accidentally.  An override file is defined for each environment
# with configurations that are not common to all environments.
version: '3.7'
services:
  skill-service:
    build:
      context: .
    container_name: skill-service
    depends_on:
      - skill-db
    image: skill-service
    ports:
      - '5000:5000'
    volumes:
      - type: volume
        source: certificate_volume
        target: /etc/ssl/certs

  skill-db:
    container_name: skill-db
    image: mongo
    volumes:
      - type: bind
        source: /Users/chrisveilleux/mongodb
        target: /data/db

volumes:
  certificate_volume:
    external:
      name: ssl_test_volume